export {default as Navbar} from './Navbar.jsx'
export {default as AboutSection} from './AboutSection.jsx'
export {default as Footer} from './Footer.jsx'
export {default as HeroSection} from './HeroSection.jsx'
export {default as PopularSection} from './PopularSection.jsx'
export {default as ReviewSection} from './ReviewSection.jsx'
export {default as WhyUsSection} from './WhyUsSection.jsx'
